// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pokerchain/poker/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WithdrawalRequest represents a pending withdrawal from Cosmos to Base chain.
type WithdrawalRequest struct {
	Nonce         string `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	CosmosAddress string `protobuf:"bytes,2,opt,name=cosmos_address,json=cosmosAddress,proto3" json:"cosmos_address,omitempty"`
	BaseAddress   string `protobuf:"bytes,3,opt,name=base_address,json=baseAddress,proto3" json:"base_address,omitempty"`
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Signature     []byte `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt     int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   int64  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
}

func (m *WithdrawalRequest) Reset()         { *m = WithdrawalRequest{} }
func (m *WithdrawalRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawalRequest) ProtoMessage()    {}
func (*WithdrawalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54ec3370909f59c, []int{0}
}
func (m *WithdrawalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WithdrawalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WithdrawalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WithdrawalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalRequest.Merge(m, src)
}
func (m *WithdrawalRequest) XXX_Size() int {
	return m.Size()
}
func (m *WithdrawalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalRequest proto.InternalMessageInfo

func (m *WithdrawalRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *WithdrawalRequest) GetCosmosAddress() string {
	if m != nil {
		return m.CosmosAddress
	}
	return ""
}

func (m *WithdrawalRequest) GetBaseAddress() string {
	if m != nil {
		return m.BaseAddress
	}
	return ""
}

func (m *WithdrawalRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithdrawalRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *WithdrawalRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *WithdrawalRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *WithdrawalRequest) GetCompletedAt() int64 {
	if m != nil {
		return m.CompletedAt
	}
	return 0
}

// GenesisState defines the poker module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// Bridge state - processed Ethereum transaction hashes (prevents double-minting)
	ProcessedEthTxs []string `protobuf:"bytes,2,rep,name=processed_eth_txs,json=processedEthTxs,proto3" json:"processed_eth_txs,omitempty"`
	// Withdrawal requests - pending and completed withdrawals
	WithdrawalRequests []*WithdrawalRequest `protobuf:"bytes,3,rep,name=withdrawal_requests,json=withdrawalRequests,proto3" json:"withdrawal_requests,omitempty"`
	// Withdrawal nonce counter - increments for each new withdrawal
	WithdrawalNonce uint64 `protobuf:"varint,4,opt,name=withdrawal_nonce,json=withdrawalNonce,proto3" json:"withdrawal_nonce,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54ec3370909f59c, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetProcessedEthTxs() []string {
	if m != nil {
		return m.ProcessedEthTxs
	}
	return nil
}

func (m *GenesisState) GetWithdrawalRequests() []*WithdrawalRequest {
	if m != nil {
		return m.WithdrawalRequests
	}
	return nil
}

func (m *GenesisState) GetWithdrawalNonce() uint64 {
	if m != nil {
		return m.WithdrawalNonce
	}
	return 0
}

func init() {
	proto.RegisterType((*WithdrawalRequest)(nil), "pokerchain.poker.v1.WithdrawalRequest")
	proto.RegisterType((*GenesisState)(nil), "pokerchain.poker.v1.GenesisState")
}

func init() { proto.RegisterFile("pokerchain/poker/v1/genesis.proto", fileDescriptor_f54ec3370909f59c) }

var fileDescriptor_f54ec3370909f59c = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x77, 0xba, 0xed, 0x6a, 0x66, 0x57, 0xeb, 0x4e, 0x8b, 0x84, 0xaa, 0x31, 0x2d, 0x28,
	0xb1, 0x42, 0x42, 0x57, 0xbc, 0x0a, 0x5b, 0x28, 0xde, 0x44, 0xa2, 0x50, 0xf0, 0x12, 0x66, 0x93,
	0x47, 0x12, 0xba, 0xc9, 0xc4, 0x99, 0x97, 0xee, 0x7a, 0xf6, 0x0b, 0xf8, 0x31, 0x3c, 0xfa, 0x31,
	0x7a, 0xec, 0xd1, 0x93, 0xc8, 0xee, 0xc1, 0x6f, 0x21, 0x92, 0x99, 0xb8, 0x5b, 0x74, 0x2f, 0xe1,
	0xbd, 0xdf, 0xfc, 0x67, 0x5e, 0xf8, 0xff, 0x1f, 0x3d, 0xac, 0xc4, 0x05, 0xc8, 0x38, 0xe3, 0x79,
	0x19, 0xe8, 0x32, 0xb8, 0x3c, 0x09, 0x52, 0x28, 0x41, 0xe5, 0xca, 0xaf, 0xa4, 0x40, 0xc1, 0xf6,
	0xd6, 0x12, 0x5f, 0x97, 0xfe, 0xe5, 0xc9, 0xc1, 0x90, 0x17, 0x79, 0x29, 0x02, 0xfd, 0x35, 0xba,
	0x83, 0xfd, 0x54, 0xa4, 0x42, 0x97, 0x41, 0x53, 0xb5, 0xd4, 0xdd, 0x34, 0xa0, 0xe2, 0x92, 0x17,
	0xed, 0xfb, 0x47, 0x9f, 0xb7, 0xe8, 0xf0, 0x3c, 0xc7, 0x2c, 0x91, 0x7c, 0xc6, 0xa7, 0x21, 0x7c,
	0xac, 0x41, 0x21, 0xdb, 0xa7, 0x3b, 0xa5, 0x28, 0x63, 0xb0, 0x89, 0x4b, 0x3c, 0x2b, 0x34, 0x0d,
	0x7b, 0x42, 0xef, 0xc6, 0x42, 0x15, 0x42, 0x45, 0x3c, 0x49, 0x24, 0x28, 0x65, 0x6f, 0xe9, 0xe3,
	0x3b, 0x86, 0x8e, 0x0d, 0x64, 0x87, 0x74, 0x30, 0xe1, 0x0a, 0x56, 0xa2, 0xae, 0x16, 0xf5, 0x1b,
	0xf6, 0x57, 0x72, 0x9f, 0xf6, 0x78, 0x21, 0xea, 0x12, 0xed, 0x6d, 0x97, 0x78, 0xdb, 0x61, 0xdb,
	0x35, 0x5c, 0x21, 0xc7, 0x5a, 0xd9, 0x3b, 0xfa, 0x52, 0xdb, 0xb1, 0x87, 0xd4, 0x52, 0x79, 0x5a,
	0x72, 0xac, 0x25, 0xd8, 0x3d, 0x97, 0x78, 0x83, 0x70, 0x0d, 0xd8, 0x23, 0x4a, 0x63, 0x09, 0x1c,
	0x21, 0x89, 0x38, 0xda, 0xb7, 0x5c, 0xe2, 0x75, 0x43, 0xab, 0x25, 0x63, 0x6c, 0xfe, 0x27, 0x16,
	0x45, 0x35, 0x85, 0x56, 0x70, 0x5b, 0x0b, 0xfa, 0x2b, 0x36, 0xc6, 0xa3, 0xdf, 0x84, 0x0e, 0x5e,
	0x1b, 0xdf, 0xdf, 0x21, 0x47, 0x60, 0xaf, 0x68, 0xcf, 0xd8, 0xa4, 0x1d, 0xe8, 0x8f, 0x1e, 0xf8,
	0x1b, 0x72, 0xf0, 0xdf, 0x6a, 0xc9, 0xa9, 0x75, 0xf5, 0xe3, 0x71, 0xe7, 0xeb, 0xaf, 0x6f, 0xc7,
	0x24, 0x6c, 0x6f, 0xb1, 0x63, 0x3a, 0xac, 0xa4, 0x88, 0x41, 0x29, 0x48, 0x22, 0xc0, 0x2c, 0xc2,
	0x79, 0xe3, 0x56, 0xd7, 0xb3, 0xc2, 0xdd, 0xd5, 0xc1, 0x19, 0x66, 0xef, 0xe7, 0x8a, 0x9d, 0xd3,
	0xbd, 0xd9, 0x2a, 0x81, 0x48, 0x9a, 0x08, 0x1a, 0xdb, 0xba, 0x5e, 0x7f, 0xf4, 0x74, 0xe3, 0xe0,
	0xff, 0x12, 0x0b, 0xd9, 0xec, 0x5f, 0xa4, 0xd8, 0x33, 0x7a, 0xef, 0xc6, 0xc3, 0x26, 0x50, 0xe3,
	0xf7, 0xee, 0x9a, 0xbf, 0x69, 0xf0, 0xe9, 0xd9, 0xd5, 0xc2, 0x21, 0xd7, 0x0b, 0x87, 0xfc, 0x5c,
	0x38, 0xe4, 0xcb, 0xd2, 0xe9, 0x5c, 0x2f, 0x9d, 0xce, 0xf7, 0xa5, 0xd3, 0xf9, 0xf0, 0x3c, 0xcd,
	0x31, 0xab, 0x27, 0x7e, 0x2c, 0x8a, 0x60, 0x32, 0x15, 0xf1, 0xc5, 0xcb, 0x51, 0x70, 0x63, 0xab,
	0xe6, 0xed, 0x5e, 0xe1, 0xa7, 0x0a, 0xd4, 0xa4, 0xa7, 0x97, 0xea, 0xc5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc8, 0x44, 0x3c, 0x33, 0xd9, 0x02, 0x00, 0x00,
}

func (m *WithdrawalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WithdrawalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WithdrawalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CompletedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CompletedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.CreatedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Amount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BaseAddress) > 0 {
		i -= len(m.BaseAddress)
		copy(dAtA[i:], m.BaseAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.BaseAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CosmosAddress) > 0 {
		i -= len(m.CosmosAddress)
		copy(dAtA[i:], m.CosmosAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CosmosAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithdrawalNonce != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.WithdrawalNonce))
		i--
		dAtA[i] = 0x20
	}
	if len(m.WithdrawalRequests) > 0 {
		for iNdEx := len(m.WithdrawalRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawalRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ProcessedEthTxs) > 0 {
		for iNdEx := len(m.ProcessedEthTxs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ProcessedEthTxs[iNdEx])
			copy(dAtA[i:], m.ProcessedEthTxs[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.ProcessedEthTxs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WithdrawalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.CosmosAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.BaseAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovGenesis(uint64(m.Amount))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGenesis(uint64(m.CreatedAt))
	}
	if m.CompletedAt != 0 {
		n += 1 + sovGenesis(uint64(m.CompletedAt))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ProcessedEthTxs) > 0 {
		for _, s := range m.ProcessedEthTxs {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WithdrawalRequests) > 0 {
		for _, e := range m.WithdrawalRequests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.WithdrawalNonce != 0 {
		n += 1 + sovGenesis(uint64(m.WithdrawalNonce))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WithdrawalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WithdrawalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WithdrawalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedAt", wireType)
			}
			m.CompletedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedEthTxs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessedEthTxs = append(m.ProcessedEthTxs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalRequests = append(m.WithdrawalRequests, &WithdrawalRequest{})
			if err := m.WithdrawalRequests[len(m.WithdrawalRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalNonce", wireType)
			}
			m.WithdrawalNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
