// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pokerchain/poker/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGameRequest defines the QueryGameRequest message.
type QueryGameRequest struct {
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (m *QueryGameRequest) Reset()         { *m = QueryGameRequest{} }
func (m *QueryGameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGameRequest) ProtoMessage()    {}
func (*QueryGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{2}
}
func (m *QueryGameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameRequest.Merge(m, src)
}
func (m *QueryGameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameRequest proto.InternalMessageInfo

func (m *QueryGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

// QueryGameResponse defines the QueryGameResponse message.
type QueryGameResponse struct {
	Game string `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (m *QueryGameResponse) Reset()         { *m = QueryGameResponse{} }
func (m *QueryGameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGameResponse) ProtoMessage()    {}
func (*QueryGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{3}
}
func (m *QueryGameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameResponse.Merge(m, src)
}
func (m *QueryGameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameResponse proto.InternalMessageInfo

func (m *QueryGameResponse) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

// QueryListGamesRequest defines the QueryListGamesRequest message.
type QueryListGamesRequest struct {
}

func (m *QueryListGamesRequest) Reset()         { *m = QueryListGamesRequest{} }
func (m *QueryListGamesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListGamesRequest) ProtoMessage()    {}
func (*QueryListGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{4}
}
func (m *QueryListGamesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListGamesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListGamesRequest.Merge(m, src)
}
func (m *QueryListGamesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListGamesRequest proto.InternalMessageInfo

// QueryListGamesResponse defines the QueryListGamesResponse message.
type QueryListGamesResponse struct {
	Games string `protobuf:"bytes,1,opt,name=games,proto3" json:"games,omitempty"`
}

func (m *QueryListGamesResponse) Reset()         { *m = QueryListGamesResponse{} }
func (m *QueryListGamesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListGamesResponse) ProtoMessage()    {}
func (*QueryListGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{5}
}
func (m *QueryListGamesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListGamesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListGamesResponse.Merge(m, src)
}
func (m *QueryListGamesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListGamesResponse proto.InternalMessageInfo

func (m *QueryListGamesResponse) GetGames() string {
	if m != nil {
		return m.Games
	}
	return ""
}

// QueryPlayerGamesRequest defines the QueryPlayerGamesRequest message.
type QueryPlayerGamesRequest struct {
	PlayerAddress string `protobuf:"bytes,1,opt,name=player_address,json=playerAddress,proto3" json:"player_address,omitempty"`
}

func (m *QueryPlayerGamesRequest) Reset()         { *m = QueryPlayerGamesRequest{} }
func (m *QueryPlayerGamesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPlayerGamesRequest) ProtoMessage()    {}
func (*QueryPlayerGamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{6}
}
func (m *QueryPlayerGamesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPlayerGamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPlayerGamesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPlayerGamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPlayerGamesRequest.Merge(m, src)
}
func (m *QueryPlayerGamesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPlayerGamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPlayerGamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPlayerGamesRequest proto.InternalMessageInfo

func (m *QueryPlayerGamesRequest) GetPlayerAddress() string {
	if m != nil {
		return m.PlayerAddress
	}
	return ""
}

// QueryPlayerGamesResponse defines the QueryPlayerGamesResponse message.
type QueryPlayerGamesResponse struct {
	Games string `protobuf:"bytes,1,opt,name=games,proto3" json:"games,omitempty"`
}

func (m *QueryPlayerGamesResponse) Reset()         { *m = QueryPlayerGamesResponse{} }
func (m *QueryPlayerGamesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPlayerGamesResponse) ProtoMessage()    {}
func (*QueryPlayerGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{7}
}
func (m *QueryPlayerGamesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPlayerGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPlayerGamesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPlayerGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPlayerGamesResponse.Merge(m, src)
}
func (m *QueryPlayerGamesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPlayerGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPlayerGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPlayerGamesResponse proto.InternalMessageInfo

func (m *QueryPlayerGamesResponse) GetGames() string {
	if m != nil {
		return m.Games
	}
	return ""
}

// QueryLegalActionsRequest defines the QueryLegalActionsRequest message.
type QueryLegalActionsRequest struct {
	GameId        string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerAddress string `protobuf:"bytes,2,opt,name=player_address,json=playerAddress,proto3" json:"player_address,omitempty"`
}

func (m *QueryLegalActionsRequest) Reset()         { *m = QueryLegalActionsRequest{} }
func (m *QueryLegalActionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLegalActionsRequest) ProtoMessage()    {}
func (*QueryLegalActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{8}
}
func (m *QueryLegalActionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLegalActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLegalActionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLegalActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLegalActionsRequest.Merge(m, src)
}
func (m *QueryLegalActionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLegalActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLegalActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLegalActionsRequest proto.InternalMessageInfo

func (m *QueryLegalActionsRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *QueryLegalActionsRequest) GetPlayerAddress() string {
	if m != nil {
		return m.PlayerAddress
	}
	return ""
}

// QueryLegalActionsResponse defines the QueryLegalActionsResponse message.
type QueryLegalActionsResponse struct {
	Actions string `protobuf:"bytes,1,opt,name=actions,proto3" json:"actions,omitempty"`
}

func (m *QueryLegalActionsResponse) Reset()         { *m = QueryLegalActionsResponse{} }
func (m *QueryLegalActionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLegalActionsResponse) ProtoMessage()    {}
func (*QueryLegalActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{9}
}
func (m *QueryLegalActionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLegalActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLegalActionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLegalActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLegalActionsResponse.Merge(m, src)
}
func (m *QueryLegalActionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLegalActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLegalActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLegalActionsResponse proto.InternalMessageInfo

func (m *QueryLegalActionsResponse) GetActions() string {
	if m != nil {
		return m.Actions
	}
	return ""
}

// QueryGameStateRequest defines the QueryGameStateRequest message.
type QueryGameStateRequest struct {
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (m *QueryGameStateRequest) Reset()         { *m = QueryGameStateRequest{} }
func (m *QueryGameStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGameStateRequest) ProtoMessage()    {}
func (*QueryGameStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{10}
}
func (m *QueryGameStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGameStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGameStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGameStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameStateRequest.Merge(m, src)
}
func (m *QueryGameStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGameStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameStateRequest proto.InternalMessageInfo

func (m *QueryGameStateRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

// QueryGameStateResponse defines the QueryGameStateResponse message.
type QueryGameStateResponse struct {
	GameState string `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
}

func (m *QueryGameStateResponse) Reset()         { *m = QueryGameStateResponse{} }
func (m *QueryGameStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGameStateResponse) ProtoMessage()    {}
func (*QueryGameStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d94828f419f7527, []int{11}
}
func (m *QueryGameStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGameStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGameStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGameStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGameStateResponse.Merge(m, src)
}
func (m *QueryGameStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGameStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGameStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGameStateResponse proto.InternalMessageInfo

func (m *QueryGameStateResponse) GetGameState() string {
	if m != nil {
		return m.GameState
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "pokerchain.poker.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "pokerchain.poker.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGameRequest)(nil), "pokerchain.poker.v1.QueryGameRequest")
	proto.RegisterType((*QueryGameResponse)(nil), "pokerchain.poker.v1.QueryGameResponse")
	proto.RegisterType((*QueryListGamesRequest)(nil), "pokerchain.poker.v1.QueryListGamesRequest")
	proto.RegisterType((*QueryListGamesResponse)(nil), "pokerchain.poker.v1.QueryListGamesResponse")
	proto.RegisterType((*QueryPlayerGamesRequest)(nil), "pokerchain.poker.v1.QueryPlayerGamesRequest")
	proto.RegisterType((*QueryPlayerGamesResponse)(nil), "pokerchain.poker.v1.QueryPlayerGamesResponse")
	proto.RegisterType((*QueryLegalActionsRequest)(nil), "pokerchain.poker.v1.QueryLegalActionsRequest")
	proto.RegisterType((*QueryLegalActionsResponse)(nil), "pokerchain.poker.v1.QueryLegalActionsResponse")
	proto.RegisterType((*QueryGameStateRequest)(nil), "pokerchain.poker.v1.QueryGameStateRequest")
	proto.RegisterType((*QueryGameStateResponse)(nil), "pokerchain.poker.v1.QueryGameStateResponse")
}

func init() { proto.RegisterFile("pokerchain/poker/v1/query.proto", fileDescriptor_9d94828f419f7527) }

var fileDescriptor_9d94828f419f7527 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xd1, 0x4b, 0x14, 0x41,
	0x18, 0xbf, 0x11, 0x3d, 0xb9, 0xcf, 0x8a, 0x1c, 0x2d, 0x6d, 0xab, 0x53, 0x36, 0x4c, 0xf3, 0x72,
	0xc7, 0x53, 0x24, 0x8a, 0x88, 0x14, 0x44, 0x02, 0x83, 0x32, 0x7a, 0xf1, 0xe5, 0x98, 0xbb, 0x1b,
	0xd6, 0xc5, 0xdb, 0x9d, 0x75, 0x67, 0x95, 0x44, 0x7c, 0xe9, 0x29, 0x7a, 0x0a, 0xa2, 0xe7, 0x5e,
	0x7b, 0x8a, 0xfe, 0x80, 0xfe, 0x00, 0x7b, 0x13, 0x7a, 0xe9, 0x29, 0x42, 0x83, 0xfe, 0x8d, 0xd8,
	0x99, 0x4f, 0x5d, 0xbd, 0x75, 0xcf, 0x97, 0x63, 0xf6, 0x9b, 0xdf, 0xef, 0x37, 0xbf, 0xf9, 0xe6,
	0xfb, 0x71, 0x30, 0x12, 0xca, 0x75, 0x11, 0x35, 0xd6, 0xb8, 0x17, 0x30, 0xbd, 0x64, 0x5b, 0x55,
	0xb6, 0xb1, 0x29, 0xa2, 0x6d, 0x27, 0x8c, 0x64, 0x2c, 0xe9, 0xc0, 0x09, 0xc0, 0xd1, 0x4b, 0x67,
	0xab, 0x6a, 0xf5, 0x73, 0xdf, 0x0b, 0x24, 0xd3, 0xbf, 0x06, 0x67, 0x4d, 0x36, 0xa4, 0xf2, 0xa5,
	0x62, 0x75, 0xae, 0x84, 0x11, 0x60, 0x5b, 0xd5, 0xba, 0x88, 0x79, 0x95, 0x85, 0xdc, 0xf5, 0x02,
	0x1e, 0x7b, 0x32, 0x40, 0xec, 0xa0, 0x2b, 0x5d, 0xa9, 0x97, 0x2c, 0x59, 0x61, 0xf5, 0x96, 0x2b,
	0xa5, 0xdb, 0x12, 0x8c, 0x87, 0x1e, 0xe3, 0x41, 0x20, 0x63, 0x4d, 0x51, 0xb8, 0x3b, 0x9a, 0x65,
	0x34, 0xe4, 0x11, 0xf7, 0x11, 0x61, 0x0f, 0x02, 0x7d, 0x99, 0x9c, 0xfb, 0x42, 0x17, 0x57, 0xc4,
	0xc6, 0xa6, 0x50, 0xb1, 0xfd, 0x1a, 0x06, 0x4e, 0x55, 0x55, 0x28, 0x03, 0x25, 0xe8, 0x13, 0x28,
	0x1a, 0xf2, 0x30, 0x19, 0x25, 0x13, 0x7d, 0x33, 0x37, 0x9d, 0x8c, 0x7b, 0x3a, 0x86, 0xb4, 0x50,
	0xda, 0xfb, 0x3d, 0x52, 0xf8, 0xf2, 0xef, 0xdb, 0x24, 0x59, 0x41, 0x96, 0x5d, 0x81, 0xab, 0x5a,
	0x76, 0x89, 0xfb, 0x02, 0x8f, 0xa2, 0x43, 0xd0, 0xeb, 0x72, 0x5f, 0xd4, 0xbc, 0xa6, 0x16, 0x2d,
	0xad, 0x14, 0x93, 0xcf, 0x67, 0x4d, 0x7b, 0x1c, 0xfa, 0x53, 0x60, 0x74, 0x40, 0xa1, 0x3b, 0xd9,
	0x46, 0xa8, 0x5e, 0xdb, 0x43, 0x70, 0x4d, 0x03, 0x97, 0x3d, 0x15, 0x27, 0xe0, 0xe3, 0x5b, 0x38,
	0x70, 0xfd, 0xec, 0x06, 0xca, 0x0c, 0x42, 0x4f, 0x42, 0x55, 0xa8, 0x63, 0x3e, 0xec, 0xa7, 0x30,
	0x64, 0x6e, 0xdd, 0xe2, 0xdb, 0x22, 0x4a, 0x4b, 0xd1, 0x31, 0xb8, 0x12, 0xea, 0x6a, 0x8d, 0x37,
	0x9b, 0x91, 0x50, 0x47, 0xcc, 0xcb, 0xa6, 0x3a, 0x6f, 0x8a, 0xf6, 0x34, 0x0c, 0xb7, 0x2b, 0xe4,
	0x9e, 0xb9, 0x8a, 0x8c, 0x65, 0xe1, 0xf2, 0xd6, 0x7c, 0x43, 0x3f, 0x5e, 0xa7, 0xd6, 0x64, 0xb8,
	0xe9, 0xca, 0x72, 0x33, 0x07, 0x37, 0x32, 0xb4, 0xd1, 0xce, 0x30, 0xf4, 0x72, 0x53, 0x42, 0xf1,
	0xa3, 0x4f, 0x7b, 0x1a, 0xfb, 0x99, 0xd8, 0x7f, 0x15, 0xf3, 0xb8, 0xf3, 0x53, 0x3d, 0xc0, 0x46,
	0xa7, 0x18, 0x78, 0xca, 0x6d, 0x00, 0x4d, 0x51, 0x49, 0x15, 0x59, 0x25, 0xf7, 0x08, 0x36, 0xf3,
	0xa3, 0x17, 0x7a, 0x34, 0x93, 0xbe, 0x23, 0x50, 0x34, 0x83, 0x43, 0xc7, 0x33, 0xa7, 0xaa, 0x7d,
	0x4a, 0xad, 0x89, 0xce, 0x40, 0x63, 0xc3, 0xae, 0xbc, 0xfd, 0xf9, 0xf7, 0x63, 0xd7, 0x18, 0xbd,
	0xc3, 0xea, 0x2d, 0xd9, 0x58, 0x9f, 0x9b, 0x61, 0xe7, 0x07, 0x83, 0xbe, 0x27, 0xd0, 0x9d, 0xdc,
	0x84, 0x8e, 0x9d, 0xaf, 0x9f, 0x9a, 0x60, 0xeb, 0x6e, 0x27, 0x18, 0x9a, 0x98, 0xd5, 0x26, 0xa6,
	0x68, 0x25, 0xd7, 0x44, 0xd2, 0x1c, 0xb6, 0x83, 0x7d, 0xde, 0xa5, 0x9f, 0x08, 0x94, 0x8e, 0xe7,
	0x97, 0x4e, 0x9e, 0x7f, 0xd4, 0xd9, 0xe9, 0xb7, 0x2a, 0x17, 0xc2, 0xa2, 0x37, 0xa6, 0xbd, 0xdd,
	0xa3, 0xe3, 0xb9, 0xde, 0x5a, 0x9e, 0x8a, 0x6b, 0x7a, 0x6e, 0xe9, 0x57, 0x02, 0x7d, 0xa9, 0x29,
	0xa7, 0xf7, 0x73, 0xde, 0xa2, 0x2d, 0x4e, 0xd6, 0xd4, 0x05, 0xd1, 0xe8, 0x6e, 0x41, 0xbb, 0x7b,
	0x4c, 0x1f, 0xe5, 0x3f, 0x9f, 0x89, 0x84, 0xf6, 0xc7, 0x76, 0x4e, 0x07, 0x64, 0x97, 0x7e, 0x27,
	0x70, 0x29, 0x1d, 0x04, 0x9a, 0xe3, 0x21, 0x23, 0x8c, 0x96, 0x73, 0x51, 0x38, 0x7a, 0x7e, 0xae,
	0x3d, 0x2f, 0xd1, 0xc5, 0xfc, 0x8e, 0x26, 0xd4, 0x1a, 0x26, 0xef, 0xe4, 0xd9, 0xdb, 0xed, 0x7f,
	0x26, 0x50, 0x3a, 0x8e, 0x57, 0xde, 0x1c, 0x9c, 0x4d, 0x6d, 0xde, 0x1c, 0xb4, 0xe5, 0xd5, 0x7e,
	0xa8, 0x5d, 0xcf, 0xd2, 0x6a, 0xc7, 0x19, 0x35, 0x91, 0x3e, 0xb1, 0xbc, 0xb0, 0xb8, 0x77, 0x50,
	0x26, 0xfb, 0x07, 0x65, 0xf2, 0xe7, 0xa0, 0x4c, 0x3e, 0x1c, 0x96, 0x0b, 0xfb, 0x87, 0xe5, 0xc2,
	0xaf, 0xc3, 0x72, 0x61, 0xb5, 0xe2, 0x7a, 0xf1, 0xda, 0x66, 0xdd, 0x69, 0x48, 0x3f, 0x4b, 0xf6,
	0x0d, 0x0a, 0xc7, 0xdb, 0xa1, 0x50, 0xf5, 0xa2, 0xfe, 0x5f, 0x9a, 0xfd, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0x82, 0x5e, 0x42, 0xd3, 0x64, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Game Queries a list of Game items.
	Game(ctx context.Context, in *QueryGameRequest, opts ...grpc.CallOption) (*QueryGameResponse, error)
	// ListGames Queries a list of ListGames items.
	ListGames(ctx context.Context, in *QueryListGamesRequest, opts ...grpc.CallOption) (*QueryListGamesResponse, error)
	// PlayerGames Queries a list of PlayerGames items.
	PlayerGames(ctx context.Context, in *QueryPlayerGamesRequest, opts ...grpc.CallOption) (*QueryPlayerGamesResponse, error)
	// LegalActions Queries a list of LegalActions items.
	LegalActions(ctx context.Context, in *QueryLegalActionsRequest, opts ...grpc.CallOption) (*QueryLegalActionsResponse, error)
	// GameState Queries the detailed game state for a game.
	GameState(ctx context.Context, in *QueryGameStateRequest, opts ...grpc.CallOption) (*QueryGameStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Game(ctx context.Context, in *QueryGameRequest, opts ...grpc.CallOption) (*QueryGameResponse, error) {
	out := new(QueryGameResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/Game", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListGames(ctx context.Context, in *QueryListGamesRequest, opts ...grpc.CallOption) (*QueryListGamesResponse, error) {
	out := new(QueryListGamesResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/ListGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PlayerGames(ctx context.Context, in *QueryPlayerGamesRequest, opts ...grpc.CallOption) (*QueryPlayerGamesResponse, error) {
	out := new(QueryPlayerGamesResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/PlayerGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LegalActions(ctx context.Context, in *QueryLegalActionsRequest, opts ...grpc.CallOption) (*QueryLegalActionsResponse, error) {
	out := new(QueryLegalActionsResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/LegalActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GameState(ctx context.Context, in *QueryGameStateRequest, opts ...grpc.CallOption) (*QueryGameStateResponse, error) {
	out := new(QueryGameStateResponse)
	err := c.cc.Invoke(ctx, "/pokerchain.poker.v1.Query/GameState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Game Queries a list of Game items.
	Game(context.Context, *QueryGameRequest) (*QueryGameResponse, error)
	// ListGames Queries a list of ListGames items.
	ListGames(context.Context, *QueryListGamesRequest) (*QueryListGamesResponse, error)
	// PlayerGames Queries a list of PlayerGames items.
	PlayerGames(context.Context, *QueryPlayerGamesRequest) (*QueryPlayerGamesResponse, error)
	// LegalActions Queries a list of LegalActions items.
	LegalActions(context.Context, *QueryLegalActionsRequest) (*QueryLegalActionsResponse, error)
	// GameState Queries the detailed game state for a game.
	GameState(context.Context, *QueryGameStateRequest) (*QueryGameStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Game(ctx context.Context, req *QueryGameRequest) (*QueryGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game not implemented")
}
func (*UnimplementedQueryServer) ListGames(ctx context.Context, req *QueryListGamesRequest) (*QueryListGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGames not implemented")
}
func (*UnimplementedQueryServer) PlayerGames(ctx context.Context, req *QueryPlayerGamesRequest) (*QueryPlayerGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerGames not implemented")
}
func (*UnimplementedQueryServer) LegalActions(ctx context.Context, req *QueryLegalActionsRequest) (*QueryLegalActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LegalActions not implemented")
}
func (*UnimplementedQueryServer) GameState(ctx context.Context, req *QueryGameStateRequest) (*QueryGameStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameState not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Game_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Game(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/Game",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Game(ctx, req.(*QueryGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/ListGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListGames(ctx, req.(*QueryListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PlayerGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPlayerGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PlayerGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/PlayerGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PlayerGames(ctx, req.(*QueryPlayerGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LegalActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLegalActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LegalActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/LegalActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LegalActions(ctx, req.(*QueryLegalActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokerchain.poker.v1.Query/GameState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GameState(ctx, req.(*QueryGameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pokerchain.poker.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Game",
			Handler:    _Query_Game_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _Query_ListGames_Handler,
		},
		{
			MethodName: "PlayerGames",
			Handler:    _Query_PlayerGames_Handler,
		},
		{
			MethodName: "LegalActions",
			Handler:    _Query_LegalActions_Handler,
		},
		{
			MethodName: "GameState",
			Handler:    _Query_GameState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pokerchain/poker/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GameId) > 0 {
		i -= len(m.GameId)
		copy(dAtA[i:], m.GameId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GameId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Game) > 0 {
		i -= len(m.Game)
		copy(dAtA[i:], m.Game)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Game)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListGamesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListGamesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListGamesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryListGamesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListGamesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListGamesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Games) > 0 {
		i -= len(m.Games)
		copy(dAtA[i:], m.Games)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Games)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPlayerGamesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPlayerGamesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPlayerGamesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PlayerAddress) > 0 {
		i -= len(m.PlayerAddress)
		copy(dAtA[i:], m.PlayerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PlayerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPlayerGamesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPlayerGamesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPlayerGamesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Games) > 0 {
		i -= len(m.Games)
		copy(dAtA[i:], m.Games)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Games)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLegalActionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLegalActionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLegalActionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PlayerAddress) > 0 {
		i -= len(m.PlayerAddress)
		copy(dAtA[i:], m.PlayerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PlayerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.GameId) > 0 {
		i -= len(m.GameId)
		copy(dAtA[i:], m.GameId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GameId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLegalActionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLegalActionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLegalActionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actions) > 0 {
		i -= len(m.Actions)
		copy(dAtA[i:], m.Actions)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Actions)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGameStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGameStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGameStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GameId) > 0 {
		i -= len(m.GameId)
		copy(dAtA[i:], m.GameId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GameId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGameStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGameStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGameStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GameState) > 0 {
		i -= len(m.GameState)
		copy(dAtA[i:], m.GameState)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GameState)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GameId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Game)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListGamesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryListGamesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Games)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPlayerGamesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PlayerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPlayerGamesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Games)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLegalActionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GameId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PlayerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLegalActionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Actions)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGameStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GameId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGameStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GameState)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Game", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Game = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListGamesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListGamesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListGamesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListGamesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListGamesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListGamesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Games", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Games = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPlayerGamesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPlayerGamesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPlayerGamesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPlayerGamesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPlayerGamesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPlayerGamesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Games", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Games = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLegalActionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLegalActionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLegalActionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLegalActionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLegalActionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLegalActionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGameStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGameStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGameStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGameStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGameStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGameStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameState", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
