validation: sovereign
version: 1
accounts:
    - name: alice
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: cement shadow leave crash crisp aisle model hip lend february library ten cereal soul bind boil bargain barely rookie odor panda artwork damage reason
    - name: bob
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: vanish legend pelican blush control spike useful usage into any remove wear flee short october naive swear wall spy cup sort avoid agent credit
    - name: charlie
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: video short denial minimum vague arm dose parrot poverty saddle kingdom life buyer globe fashion topic vicious theme voice keep try jacket fresh potato
    - name: diana
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: twice bacon whale space improve galaxy liberty trumpet outside sunny action reflect doll hill ugly torch ride gossip snack fork talk market proud nothing
    - name: eve
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: raven mix autumn dismiss degree husband street slender maple muscle inch radar winner agent claw permit autumn expose power minute master scrub asthma retreat
    - name: frank
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: alpha satoshi civil spider expand bread pitch keen define helmet tourist rib habit cereal impulse earn milk need obscure ski purchase question vocal author
    - name: grace
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: letter stumble apology garlic liquid loyal bid board silver web ghost jewel lift direct green silk urge guitar nest erase remind jaguar decrease skin
    - name: henry
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: access execute loyal tag grid demise cloth desk dolphin pelican trumpet frown note level sibling dumb upon unfold wedding party success hint need fruit
    - name: iris
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: any antenna globe forget neglect race advice admit market guilt clay tunnel anxiety aim morning scrap visit sibling royal during proud flee maid fiscal
    - name: jack
      coins:
        - 100000000usdc
        - 10000000000000b52Token
      mnemonic: digital option before hawk alcohol uncover expire faint enact shield bike uncle kangaroo museum domain heart purchase under answer topple timber hole height glance
faucet:
    name: alice
    coins:
        - 5000000usdc
        - 1000000000b52Token
client:
    typescript:
        path: ts-client
    openapi:
        path: docs/static/openapi.json
default_denom: b52Token
validators:
    - name: alice
      bonded: 5000000000000b52Token
