name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write  # Required for uploading release assets

jobs:
  build:
    name: Build Multi-Architecture Binaries
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          # Linux builds
          - os: linux
            arch: amd64
            output: pokerchaind-linux-amd64
          - os: linux
            arch: arm64
            output: pokerchaind-linux-arm64
          
          # macOS builds
          - os: darwin
            arch: amd64
            output: pokerchaind-darwin-amd64
          - os: darwin
            arch: arm64
            output: pokerchaind-darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Adjust to your Go version
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -o build/${{ matrix.output }} \
            -ldflags "-X github.com/block52/pokerchain/cmd/pokerchaind/cmd.Version=${{ github.ref_name }}" \
            ./cmd/pokerchaind

      - name: Generate checksum
        run: |
          cd build
          sha256sum ${{ matrix.output }} > ${{ matrix.output }}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: |
            build/${{ matrix.output }}
            build/${{ matrix.output }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find release-artifacts -type f -exec cp {} release/ \;
          ls -lh release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Pokerchain ${{ github.ref_name }}
            
            ### Downloads
            
            Choose the binary for your system:
            
            **Linux:**
            - `pokerchaind-linux-amd64` - Linux x86_64 (Intel/AMD)
            - `pokerchaind-linux-arm64` - Linux ARM64 (AWS Graviton, Raspberry Pi, etc.)
            
            **macOS:**
            - `pokerchaind-darwin-amd64` - macOS Intel
            - `pokerchaind-darwin-arm64` - macOS Apple Silicon (M1/M2/M3)
            
            ### Installation
            
            ```bash
            # Download for your platform (example: Linux AMD64)
            wget https://github.com/block52/pokerchain/releases/download/${{ github.ref_name }}/pokerchaind-linux-amd64
            
            # Verify checksum
            wget https://github.com/block52/pokerchain/releases/download/${{ github.ref_name }}/pokerchaind-linux-amd64.sha256
            sha256sum -c pokerchaind-linux-amd64.sha256
            
            # Install
            chmod +x pokerchaind-linux-amd64
            sudo mv pokerchaind-linux-amd64 /usr/local/bin/pokerchaind
            
            # Verify
            pokerchaind version
            ```
            
            ### Checksums
            
            All binaries include `.sha256` checksum files for verification.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Build and push Docker images for multi-arch
  docker:
    name: Build Docker Images
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max